name: PHP Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-cache:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          id: cache
          path: vendor
          key: php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php-${{ hashFiles('**/composer.lock') }}
      - name: update autoload or Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: (test -d vendor && (composer dump-autoload)) || (composer install --no-dev --prefer-dist --no-progress --no-suggest)
     
  test:
    needs: check-cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
         - php: "7.3"
           jit: 0
         - php: "7.4"
           jit: 0
         - php: "8.0"
           jit: 1205

    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer, phpstan, phpunit:8.5.15
        ini-values: opcache.enable_cli=1, opcache.enable_cli=1, opcache.jit=${{ matrix.jit }}, opcache.jit_buffer_size=64M
        coverage: none
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          php-${{ hashFiles('**/composer.lock') }}
    
    - name: update autoload or Install dependencies
      run: (test -d vendor && (composer dump-autoload)) || (composer install --no-dev --prefer-dist --no-progress --no-suggest)

    - name: Run phpstan test
      run: phpstan analyze --no-progress --memory-limit=2G
      
    - name: Run phpunit test
      run: phpunit
